[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache = true
cache_path = "cache"
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.15"
auto_detect_remappings = true
evm_version = "shanghai"

# Optional: Enable verbose output during debugging
verbosity = 2

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
